environment:
  version: 20170624
  affix: jreq
  ext: dll
  dir: $(affix)-v$(version)-$(platform)
  zip: $(affix)-v$(version)-win-java-v$(jdk_ver)-$(platform).zip
  matrix:
    - jdk_ver: "1.8.0"
    - jdk_ver: "1.7.0"
    - jdk_ver: "1.6.0"

platform:
- x86
- x64

configuration: Release

os :
- Visual Studio 2017
- Visual Studio 2015
- Visual Studio 2013

test_script:
- set oddity=
- if "%platform%"=="x86" set oddity= (x86)
- set JDK="Program Files%oddity%/Java/jdk%jdk_ver%/bin/"
- echo %JDK%
- C:/%JDK%javac src/*.java -d .
- C:/%JDK%java JREqTest
# - java -Djava.library.path=x64/Release JREqTest

# matrix:
  # allow_failures:
  # - os: Visual Studio 2017

skip_tags: true

after_build:
- mkdir %dir% || exit 1
- cp %affix%.%ext% *.class %dir%\%affix%.%ext% || exit 1
- 7z a %zip% %dir%

artifacts:
- path: $(zip)

deploy:
  tag: v$(version)
  description: ''
  provider: GitHub
  auth_token:
    secure: kKebvPLjikQbZ7E1Vm8omoYc9K0wOcKxjWsglp3+D4fV9ev/FaWr8ZBI+AseOTis
  draft: false
  prerelease: false
  on:
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
	