# jreq.travis

matrix:
  include: 
    - os: linux
      dist: trusty
      compiler: g++
    - os: linux
      dist: trusty
      compiler: g++
      jdk: openjdk7
    - os: linux
      compiler: clang++
      dist: trusty
# Probably due to 'language' setting below, despite above line, the 'CXX' environment have to be set .
      env: CXX=clang++
    - os: osx
      compiler: clang++  

language: java

script:
- make -j
- java -Djava.library.path=. Test
# - java JREqTest

# To disable building on tags. Tags are supposed to begin with 'v' and only containing digits.
branches:
  except:
    - /^v[0-9]/
